"""DataSight GitHub PR channel — creates PRs for proposed fixes."""

from __future__ import annotations

import logging
from datasight.config.settings import get_settings

logger = logging.getLogger("datasight.approval.github_pr")


def create_github_pr(incident) -> None:
    """Create a GitHub Pull Request with the proposed fix."""
    settings = get_settings()
    if not settings.git_enabled or not settings.git_token:
        logger.warning("Git not configured for GitHub PR channel")
        return

    try:
        from datasight.git.git_client import GitClient

        git = GitClient()
        branch_name = f"{settings.git_branch_prefix}/{incident.dag_id}-{incident.id}"

        for patch in incident.patches:
            git.commit_fix(
                filepath=patch.filepath,
                message=f"datasight: {patch.description}",
                branch=branch_name,
            )

        # Create PR via GitHub API
        if settings.git_repo_url and settings.git_token:
            import requests
            from urllib.parse import urlparse

            parsed = urlparse(settings.git_repo_url)
            path_parts = parsed.path.strip("/").replace(".git", "").split("/")
            if len(path_parts) >= 2:
                owner, repo = path_parts[0], path_parts[1]

                pr_body = f"""## 🤖 DataSight AI Auto-Fix

**DAG:** `{incident.dag_id}`
**Task:** `{incident.task_id}`
**Severity:** {incident.severity}

### Root Cause
{incident.root_cause}

### Explanation
{incident.explanation}

### Changes
{incident.patches[0].description if incident.patches else 'No code changes'}

---
*Generated by [DataSight AI](https://github.com/Mrnidhi/DataEngineering_Copilot)*
"""

                response = requests.post(
                    f"https://api.github.com/repos/{owner}/{repo}/pulls",
                    json={
                        "title": f"[DataSight] Fix {incident.dag_id}.{incident.task_id}",
                        "body": pr_body,
                        "head": branch_name,
                        "base": "main",
                    },
                    headers={
                        "Authorization": f"token {settings.git_token}",
                        "Accept": "application/vnd.github+json",
                    },
                    timeout=10,
                )
                if response.ok:
                    pr_url = response.json().get("html_url", "")
                    logger.info("GitHub PR created: %s", pr_url)
                else:
                    logger.error("Failed to create PR: %s", response.text)

    except Exception as e:
        logger.error("GitHub PR channel error: %s", e)
