apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasync-api
  namespace: datasync
  labels:
    app.kubernetes.io/name: datasync
    app.kubernetes.io/component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: datasync
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datasync
        app.kubernetes.io/component: api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 50000
      containers:
        - name: api
          image: ghcr.io/mrnidhi/datasync:0.1.0
          imagePullPolicy: IfNotPresent
          command: ["uvicorn", "datasight.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - configMapRef:
                name: datasync-config
            - secretRef:
                name: datasync-secrets
                optional: true
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
---
apiVersion: v1
kind: Service
metadata:
  name: datasync-api
  namespace: datasync
  labels:
    app.kubernetes.io/name: datasync
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: datasync
    app.kubernetes.io/component: api
